# **Módulo 2. Plataformas de Aplicación sobre Python**
**Práctica 2 - Vacunación por país**
---

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Leer el archivo country_vaccinations.csv

In [ ]:
vacunas = pd.read_csv('/content/country_vaccinations.csv')

In [ ]:
vacunas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3081 entries, 0 to 3080
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              3081 non-null   object
 1   iso_code                             2833 non-null   object
 2   date                                 3081 non-null   object
 3   total_vaccinations                   1980 non-null   float64
 4   people_vaccinated                    1643 non-null   float64
 5   people_fully_vaccinated              1016 non-null   float64
 6   daily_vaccinations_raw               1642 non-null   float64
 7   daily_vaccinations                   2960 non-null   float64
 8   total_vaccinations_per_hundred       1980 non-null   float64
 9   people_vaccinated_per_hundred        1643 non-null   float64
 10  people_fully_vaccinated_per_hundred  1016 non-null   float64
 11  daily_vaccinations_per_million       2960 non-null   float64
 12  vaccines                             3081 non-null   object
 13  source_name                          3081 non-null   object
 14  source_website                       3081 non-null   object
dtypes: float64(9), object(6)
memory usage: 361.2+ KB

In [ ]:
vacunas.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Albania,ALB,2021-01-10,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
1,Albania,ALB,2021-01-11,NaN,NaN,NaN,NaN,64.0,NaN,NaN,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
2,Albania,ALB,2021-01-12,128.0,128.0,NaN,NaN,64.0,0.00,0.00,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
3,Albania,ALB,2021-01-13,188.0,188.0,NaN,60.0,63.0,0.01,0.01,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
4,Albania,ALB,2021-01-14,266.0,266.0,NaN,78.0,66.0,0.01,0.01,NaN,23.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...

La cantidad de vacunas (COMO LO REPORTA CADDA PAIS EN LA COLUMNA vaccines) aplicadas de cada compañia

In [ ]:
vacunas[['vaccines', 'daily_vaccinations']].groupby('vaccines').sum()

                                                    daily_vaccinations
vaccines
Covaxin, Oxford/AstraZeneca                                  7536062.0
Moderna, Oxford/AstraZeneca, Pfizer/BioNTech                17048554.0
Moderna, Pfizer/BioNTech                                    53312456.0
Oxford/AstraZeneca                                            834755.0
Oxford/AstraZeneca, Pfizer/BioNTech                         28254979.0
Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/...           3950325.0
Oxford/AstraZeneca, Sinopharm/Beijing                        1008119.0
Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V               27232.0
Oxford/AstraZeneca, Sinovac                                  4209095.0
Oxford/AstraZeneca, Sputnik V                                  65000.0
Pfizer/BioNTech                                              2468639.0
Pfizer/BioNTech, Sinopharm/Beijing                            197807.0
Pfizer/BioNTech, Sinopharm/Beijing, Sputnik V                 693501.0
Pfizer/BioNTech, Sinovac                                     1361458.0
Sinopharm/Beijing                                              64674.0
Sinopharm/Beijing, Sinopharm/Wuhan, Sinovac                 34922496.0
Sinovac                                                      4952156.0
Sputnik V                                                    4166300.0

La cantidad de vacunas aplicadas en todo el mundo

In [ ]:
vacunas['daily_vaccinations'].sum()

165073608.0

El promedio de vacunas DIARIAS aplicadas por país

In [ ]:
vacunas[['country', 'daily_vaccinations']].groupby('country').mean()

                          daily_vaccinations
country
Albania                            44.625000
Algeria                            30.000000
Andorra                            51.750000
Anguilla                          149.000000
Argentina                       12705.630435
...                                      ...
Turks and Caicos Islands          222.000000
United Arab Emirates           101290.384615
United Kingdom                 226934.098361
United States                  820716.618182
Wales                           10869.114754

[90 rows x 1 columns]

La cantidad de vacunas aplicadas el día 29/01/21 en todo el mundo

In [ ]:
vacFec = vacunas.loc[vacunas['date']=='2021-01-29', ['country', 'daily_vaccinations']]
vacFec['daily_vaccinations'].sum()

4634618.0

In [ ]:
vacunas2 = pd.read_csv('/content/country_vaccinations.csv', parse_dates=['date'])
vacunas2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3081 entries, 0 to 3080
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              3081 non-null   object
 1   iso_code                             2833 non-null   object
 2   date                                 3081 non-null   datetime64[ns]
 3   total_vaccinations                   1980 non-null   float64
 4   people_vaccinated                    1643 non-null   float64
 5   people_fully_vaccinated              1016 non-null   float64
 6   daily_vaccinations_raw               1642 non-null   float64
 7   daily_vaccinations                   2960 non-null   float64
 8   total_vaccinations_per_hundred       1980 non-null   float64
 9   people_vaccinated_per_hundred        1643 non-null   float64
 10  people_fully_vaccinated_per_hundred  1016 non-null   float64
 11  daily_vaccinations_per_million       2960 non-null   float64
 12  vaccines                             3081 non-null   object
 13  source_name                          3081 non-null   object
 14  source_website                       3081 non-null   object
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 361.2+ KB

In [ ]:
vacunas['date'] = pd.to_datetime(vacunas['date'])
vacunas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3081 entries, 0 to 3080
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              3081 non-null   object
 1   iso_code                             2833 non-null   object
 2   date                                 3081 non-null   datetime64[ns]
 3   total_vaccinations                   1980 non-null   float64
 4   people_vaccinated                    1643 non-null   float64
 5   people_fully_vaccinated              1016 non-null   float64
 6   daily_vaccinations_raw               1642 non-null   float64
 7   daily_vaccinations                   2960 non-null   float64
 8   total_vaccinations_per_hundred       1980 non-null   float64
 9   people_vaccinated_per_hundred        1643 non-null   float64
 10  people_fully_vaccinated_per_hundred  1016 non-null   float64
 11  daily_vaccinations_per_million       2960 non-null   float64
 12  vaccines                             3081 non-null   object
 13  source_name                          3081 non-null   object
 14  source_website                       3081 non-null   object
dtypes: datetime64[ns](1), float64(9), object(5)
memory usage: 361.2+ KB

In [ ]:
vacunas['date'].min()

Timestamp('2020-12-13 00:00:00')

In [ ]:
vacunas['date'].max()

Timestamp('2021-02-13 00:00:00')

In [ ]:
vacunas['date'].max() - vacunas['date'].min()

Timedelta('62 days 00:00:00')

In [ ]:
vacunas['date'].dt.year

0       2021
1       2021
2       2021
3       2021
4       2021
        ...
3076    2021
3077    2021
3078    2021
3079    2021
3080    2021
Name: date, Length: 3081, dtype: int64

In [ ]:
vacunas[vacunas['date']<'2020-12-20']

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
406,Canada,CAN,2020-12-19,NaN,8734.0,NaN,NaN,NaN,NaN,0.02,NaN,NaN,"Moderna, Pfizer/BioNTech",Government of Canada,https://health-infobase.canada.ca/covid-19/vac...
543,China,CHN,2020-12-15,1500000.0,NaN,NaN,NaN,NaN,0.10,NaN,NaN,NaN,"Sinopharm/Beijing, Sinopharm/Wuhan, Sinovac",National Health Commission,https://www.reuters.com/article/health-coronav...
544,China,CHN,2020-12-16,NaN,NaN,NaN,NaN,187500.0,NaN,NaN,NaN,130.0,"Sinopharm/Beijing, Sinopharm/Wuhan, Sinovac",National Health Commission,https://www.reuters.com/article/health-coronav...
545,China,CHN,2020-12-17,NaN,NaN,NaN,NaN,187500.0,NaN,NaN,NaN,130.0,"Sinopharm/Beijing, Sinopharm/Wuhan, Sinovac",National Health Commission,https://www.reuters.com/article/health-coronav...
546,China,CHN,2020-12-18,NaN,NaN,NaN,NaN,187500.0,NaN,NaN,NaN,130.0,"Sinopharm/Beijing, Sinopharm/Wuhan, Sinovac",National Health Commission,https://www.reuters.com/article/health-coronav...
547,China,CHN,2020-12-19,NaN,NaN,NaN,NaN,187500.0,NaN,NaN,NaN,130.0,"Sinopharm/Beijing, Sinopharm/Wuhan, Sinovac",National Health Commission,https://www.reuters.com/article/health-coronav...
847,England,NaN,2020-12-13,55389.0,55389.0,NaN,NaN,NaN,0.10,0.10,NaN,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
848,England,NaN,2020-12-14,NaN,NaN,NaN,NaN,74067.0,NaN,NaN,NaN,1316.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
849,England,NaN,2020-12-15,NaN,NaN,NaN,NaN,74067.0,NaN,NaN,NaN,1316.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
850,England,NaN,2020-12-16,NaN,NaN,NaN,NaN,74067.0,NaN,NaN,NaN,1316.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
851,England,NaN,2020-12-17,NaN,NaN,NaN,NaN,74067.0,NaN,NaN,NaN,1316.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
852,England,NaN,2020-12-18,NaN,NaN,NaN,NaN,74067.0,NaN,NaN,NaN,1316.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
853,England,NaN,2020-12-19,NaN,NaN,NaN,NaN,74067.0,NaN,NaN,NaN,1316.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
1432,Israel,ISR,2020-12-19,58.0,58.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,"Moderna, Pfizer/BioNTech",Government of Israel,https://datadashboard.health.gov.il/COVID-19/g...
1927,Northern Ireland,NaN,2020-12-13,3623.0,3623.0,NaN,NaN,NaN,0.19,0.19,NaN,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
1928,Northern Ireland,NaN,2020-12-14,NaN,NaN,NaN,NaN,1778.0,NaN,NaN,NaN,939.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
1929,Northern Ireland,NaN,2020-12-15,NaN,NaN,NaN,NaN,1778.0,NaN,NaN,NaN,939.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
1930,Northern Ireland,NaN,2020-12-16,NaN,NaN,NaN,NaN,1778.0,NaN,NaN,NaN,939.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
1931,Northern Ireland,NaN,2020-12-17,NaN,NaN,NaN,NaN,1778.0,NaN,NaN,NaN,939.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
1932,Northern Ireland,NaN,2020-12-18,NaN,NaN,NaN,NaN,1778.0,NaN,NaN,NaN,939.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
1933,Northern Ireland,NaN,2020-12-19,NaN,NaN,NaN,NaN,1778.0,NaN,NaN,NaN,939.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2300,Russia,RUS,2020-12-15,28500.0,28500.0,NaN,NaN,NaN,0.02,0.02,NaN,NaN,Sputnik V,Russian Direct Investment Fund,https://www.reuters.com/article/health-coronav...
2301,Russia,RUS,2020-12-16,NaN,NaN,NaN,NaN,3357.0,NaN,NaN,NaN,23.0,Sputnik V,Russian Direct Investment Fund,https://www.reuters.com/article/health-coronav...
2302,Russia,RUS,2020-12-17,NaN,NaN,NaN,NaN,3357.0,NaN,NaN,NaN,23.0,Sputnik V,Russian Direct Investment Fund,https://www.reuters.com/article/health-coronav...
2303,Russia,RUS,2020-12-18,NaN,NaN,NaN,NaN,3357.0,NaN,NaN,NaN,23.0,Sputnik V,Russian Direct Investment Fund,https://www.reuters.com/article/health-coronav...
2304,Russia,RUS,2020-12-19,NaN,NaN,NaN,NaN,3357.0,NaN,NaN,NaN,23.0,Sputnik V,Russian Direct Investment Fund,https://www.reuters.com/article/health-coronav...
2396,Scotland,NaN,2020-12-13,18996.0,18996.0,NaN,NaN,NaN,0.35,0.35,NaN,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2397,Scotland,NaN,2020-12-14,NaN,NaN,NaN,NaN,5873.0,NaN,NaN,NaN,1075.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2398,Scotland,NaN,2020-12-15,NaN,NaN,NaN,NaN,5873.0,NaN,NaN,NaN,1075.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2399,Scotland,NaN,2020-12-16,NaN,NaN,NaN,NaN,5873.0,NaN,NaN,NaN,1075.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2400,Scotland,NaN,2020-12-17,NaN,NaN,NaN,NaN,5873.0,NaN,NaN,NaN,1075.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2401,Scotland,NaN,2020-12-18,NaN,NaN,NaN,NaN,5873.0,NaN,NaN,NaN,1075.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2402,Scotland,NaN,2020-12-19,NaN,NaN,NaN,NaN,5873.0,NaN,NaN,NaN,1075.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2901,United Kingdom,GBR,2020-12-13,86215.0,86215.0,NaN,NaN,NaN,0.13,0.13,NaN,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2902,United Kingdom,GBR,2020-12-14,NaN,NaN,NaN,NaN,83940.0,NaN,NaN,NaN,1236.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2903,United Kingdom,GBR,2020-12-15,NaN,NaN,NaN,NaN,83940.0,NaN,NaN,NaN,1236.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2904,United Kingdom,GBR,2020-12-16,NaN,NaN,NaN,NaN,83940.0,NaN,NaN,NaN,1236.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2905,United Kingdom,GBR,2020-12-17,NaN,NaN,NaN,NaN,83940.0,NaN,NaN,NaN,1236.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2906,United Kingdom,GBR,2020-12-18,NaN,NaN,NaN,NaN,83940.0,NaN,NaN,NaN,1236.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
2907,United Kingdom,GBR,2020-12-19,NaN,NaN,NaN,NaN,83940.0,NaN,NaN,NaN,1236.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
3019,Wales,NaN,2020-12-13,8207.0,8207.0,NaN,NaN,NaN,0.26,0.26,NaN,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
3020,Wales,NaN,2020-12-14,NaN,NaN,NaN,NaN,2223.0,NaN,NaN,NaN,705.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
3021,Wales,NaN,2020-12-15,NaN,NaN,NaN,NaN,2223.0,NaN,NaN,NaN,705.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
3022,Wales,NaN,2020-12-16,NaN,NaN,NaN,NaN,2223.0,NaN,NaN,NaN,705.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
3023,Wales,NaN,2020-12-17,NaN,NaN,NaN,NaN,2223.0,NaN,NaN,NaN,705.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
3024,Wales,NaN,2020-12-18,NaN,NaN,NaN,NaN,2223.0,NaN,NaN,NaN,705.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
3025,Wales,NaN,2020-12-19,NaN,NaN,NaN,NaN,2223.0,NaN,NaN,NaN,705.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...

Una columna derivada con las diferencias de aplicación entre las columnas daily_vaccionations y daily_vaccionations_row

In [ ]:
vacunas['diferencia'] = vacunas['daily_vaccinations_raw'] - vacunas['daily_vaccinations']
vacunas

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website,diferencia
0,Albania,ALB,2021-01-10,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...,NaN
1,Albania,ALB,2021-01-11,NaN,NaN,NaN,NaN,64.0,NaN,NaN,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...,NaN
2,Albania,ALB,2021-01-12,128.0,128.0,NaN,NaN,64.0,0.00,0.00,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...,NaN
3,Albania,ALB,2021-01-13,188.0,188.0,NaN,60.0,63.0,0.01,0.01,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...,-3.0
4,Albania,ALB,2021-01-14,266.0,266.0,NaN,78.0,66.0,0.01,0.01,NaN,23.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3076,Wales,NaN,2021-02-08,632251.0,628760.0,3491.0,25483.0,27364.0,20.05,19.94,0.11,8679.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...,-1881.0
3077,Wales,NaN,2021-02-09,659106.0,655419.0,3687.0,26855.0,27921.0,20.90,20.79,0.12,8856.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...,-1066.0
3078,Wales,NaN,2021-02-10,687892.0,684097.0,3795.0,28786.0,28015.0,21.82,21.70,0.12,8886.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...,771.0
3079,Wales,NaN,2021-02-11,719954.0,715944.0,4010.0,32062.0,27897.0,22.83,22.71,0.13,8848.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...,4165.0
3080,Wales,NaN,2021-02-12,753669.0,749445.0,4224.0,33715.0,27743.0,23.90,23.77,0.13,8799.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...,5972.0

La diferencia de vacunación entre los días 20/01/21 y 31/01/21 para México y EEUU

In [ ]:
MexEU = vacunas[['country', 'date', 'daily_vaccinations']]
MexEU = MexEU.query('(country=="Mexico" | country=="United States") & (date=="2021-01-20" | date=="2021-01-31")')

MexEU
#print('Diferencia para México: ', MexEU.iloc[0][2]-MexEU.iloc[1][2])
#print('Diferencia para EEUU: ', MexEU.iloc[2][2]-MexEU.iloc[3][2])

            country       date  daily_vaccinations
1800         Mexico 2021-01-20             44066.0
1811         Mexico 2021-01-31              6243.0
2994  United States 2021-01-20            892403.0
3005  United States 2021-01-31           1324949.0

In [ ]:
print('Diferencia para México: ', MexEU.iloc[0][2]-MexEU.iloc[1][2])
print('Diferencia para EEUU: ', MexEU.iloc[2][2]-MexEU.iloc[3][2])

Diferencia para México:  37823.0
Diferencia para EEUU:  -432546.0

Guardar todos los dataframe usados en formato de archivo de Excel

In [ ]:
#ExcelWriter
vacunas.to_excel('/content/datos.xlsx', sheet_name='datos1')
MexEU.to_excel('')

In [ ]:
# PARA EL RETO
# investigar la función where
# o utilizar un list comprehenssion